version: '3.7'
services:
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"

    resetdb:
        image: amazon/mwaa-local:2_8
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=4Cp90_jzIuuwgpSgVIzCOX9CaWBQmIL5Xlm6p7MzY1s=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/../airflow/dags:/usr/local/airflow/dags"
            - "${PWD}/plugins:/usr/local/airflow/plugins"
            - "${PWD}/../airflow/requirements.txt:/usr/local/airflow/requirements/requirements.txt"
        ports:
            - "8080:8080"
        command: resetdb
